class WorldData {
    static readonly screenMode: number; // = 0; 移动端屏幕布局模式
    static readonly sceneBGMGradientTime: number; // = 0; BGM过渡时间
    static readonly sceneBGSGradientTime: number; // = 0; BGS过渡时间
    static readonly moveToGridCenter: boolean; // = false; 移动至格子中心点
    static readonly moveDir4: boolean; // = false; 四方向移动
    static readonly jumpTimeCost: number; // = 0; 跳跃花费的时间
    static readonly jumpHeight: number; // = 0; 跳跃高度
    static menuEnabled: boolean; // = true;
    static readonly sceneObjectCollisionSize: number; // = 32; 场景对象碰撞范围
    static readonly sceneObjectMoveStartAct: number; // = 2; 行走动作
    static readonly useSceneObjectMoveStartAct2: boolean; // = false; 开启奔跑动作
    static readonly sceneObjectMoveStartAct2Speed: number; // = 0; 奔跑时的速度
    static readonly sceneObjectMoveStartAct2: number; // = 0; 奔跑动作
    static readonly selectSceneObjectEffect: number; // = 0; 场景对象悬停动画
    static readonly saveFileMax: number; // = 10; 存档总数
    static playCtrlEnabled: boolean; // = true;
    static readonly uiCompFocusAnimation: number; // = 0; 界面组件焦点动画
    static gridObsDebug: boolean; // = false; 显示地图格子障碍
    static rectObsDebug: boolean; // = false; 显示对象碰撞盒
    static dragSceneObjectDebug: boolean; // = false; 鼠标左键拖拽对象
    static zoomCameraDebug: boolean; // = false; 滚轮缩放镜头
    static readonly focusEnabled: boolean; // = false; 使用按钮焦点
    static readonly hotKeyListEnabled: boolean; // = false; 允许按键操作列表
    static readonly sceneObjectMoveStartAct2FPS: number; // = 20; 奔跑时的帧率
    static readonly banCollisionSetting: DataStructure_collisionGroupSetting[]; // = [];
    static readonly selectSE: string; // = ""; 光标
    static readonly sureSE: string; // = ""; 确定
    static readonly cancelSE: string; // = ""; 取消
    static readonly disalbeSE: string; // = ""; 禁用
    static readonly dialogSE: string; // = ""; 文本播放音效
    static dialogSEEnabled: boolean; // = true;
    static readonly equipSE: string; // = ""; 穿上装备
    static readonly unequipSE: string; // = ""; 卸下装备
    static readonly getItemSE: string; // = ""; 获得道具
    static readonly swapItemSE: string; // = ""; 交换道具
    static readonly discardItemSE: string; // = ""; 丢弃道具
    static readonly pickupItemSE: string; // = ""; 拾取道具
    static keyboards: DataStructure_gameKeyboard[]; // = [];
    static bak1: number; // = 0; 准备阶段角色上场提示
    static bak2: number; // = 0; 准备阶段更换角色位置提示
    static bak3: number; // = 0; 准备阶段移动端提示
    static bak4: string; // = ""; 准备阶段更换角色朝向提示
    static deadPlayerActorLeaveParty: boolean; // = true; 死亡的玩家角色自动离开队伍
    static readonly iconDisabledAni: number; // = 1; 图标禁用时动画效果
    static showVigilanceRange: boolean; // = false; 显示警戒范围
    static vigilanceColor: string; // = "#FFFF00"; 警戒范围颜色
    static vigilanceAlpha: number; // = 0.3; 警戒范围透明度
    static displayBattlerPointBar: boolean; // = true; 显示战斗者血条
    static whenDeadContinue: boolean; // = false; 阵亡后继续游戏
    static equipQualitySetting: DataStructure_equipQualitySetting[]; // = [];
    static hitEffect: boolean; // = false; 击中效果（硬直）
    static hitEffectTarget: number; // = 0; 作用目标
    static hitEffectMode: number; // = 0; 效果模式
    static readonly hitAnimation: number; // = 1033; 受击动画
    static onMobileScale: number; // = 2; 移动端缩放比例
    static onPCScale: number; // = 1; 电脑端缩放比例
    static displayBattlerPointValue: boolean; // = true; 显示战斗者血条数值
    static shoutDistance: number; // = 100; 呐喊距离
    static shoutReactionTime: number; // = 1.5; 呐喊反应时间
    static battleMode: number; // = 0;
    static dropGoldSetting: DataStructure_drapGold[]; // = [];
    static dropItemDisposeTime: number; // = 10; 掉落道具销毁时间
    static battleKeyboardSetting: DataStructure_battleKeyboard[]; // = [];
    static showSkillNum: number; // = 3; 显示技能数
    static battleAutoHideParty: boolean; // = false;
    static sceneItemSize: number; // = 24; 掉落道具图标的尺寸
    static sceneItemSpace: number; // = 32; 掉落道具图标的间距
    static battleOriMode: number; // = 1; 战斗者朝向模式
    static sceneItemLayer: number; // = 0; 掉落道具图标的层次
    static leftMouseClick: number; // = 14019; 鼠标左键
    static rightMouseClick: number; // = 14018; 鼠标右键
    static extendsAttributeSetting: DataStructure_customAttributeSetting[]; // = [];
    static showDamageType: number; // = 1;
    static useCustomDamageLogic: boolean; // = false; 使用自定义伤害计算
    static customDamageLogicEvent: string; // = ""; 自定义伤害逻辑
    static word_cost: string; // = ""; 消耗
    static word_gamepadInput: string; // = ""; 请按下游戏手柄键位
    static word_keyboardInput: string; // = ""; 请输入键盘键位
    static word_get: string; // = ""; 获得
    static word_totalCD: string; // = ""; 冷却
    static word_equiped: string; // = ""; 已佩戴
    static word_maxHP: string; // = ""; 最大生命值
    static word_maxSP: string; // = ""; 最大魔法值
    static word_atk: string; // = ""; 攻击力
    static word_def: string; // = ""; 防御
    static word_mag: string; // = ""; 魔力
    static word_magDef: string; // = ""; 魔法防御力
    static word_atkSpeed: string; // = ""; 攻击速度
    static word_hit: string; // = ""; 命中
    static word_crit: string; // = ""; 暴击
    static word_magCrit: string; // = ""; 魔法暴击率
    static word_moveSpeed: string; // = ""; 移动速度
    static word_hp: string; // = ""; 生命值
    static word_sp: string; // = ""; 魔法值
    static word_dod: string; // = ""; 回避
    static const_fp_game: number; // = 15001; 作品支持度
    static const_fp_user: number; // = 15002; 作者支持度
    static const_fp_cost_value: number; // = 15003; 消耗点数
    static const_fp_changeValue: number; // = 15004; 支持度变化值
    static const_fp_changeEvent: string; // = ""; 当变化时事件
    static Wfskp_MiniMap_Data: DataStructure_MiniMap_data[]; // = [];
    static w26_miniMapbackgroundColor: string; // = ""; 地图底色
    static Wfskp_MiniMap_picture: DataStructure_MiniMap_picture[]; // = [];
    static Wfskp_MiniMap_close: number; // = 0; 大地图关闭
    static Wfskp_MiniMap_scaleMin: number; // = 1; 缩放最小
    static Wfskp_MiniMap_scaleMax: number; // = 6; 缩放最大
    static Wfskp_MinMao_useBigMap: boolean; // = false; 使用大地图
    static Wfskp_MinMao_minDraw: boolean; // = true; 减少绘图
    static automated: boolean; // = false; 自动拾取
    static PickupRange: number; // = 0; 拾取范围
    static DelayedPickup: number; // = 5; 延迟拾取
    static OffsetX: number; // = 0; 偏移X
    static OffsetY: number; // = 0; 偏移Y
    static isTypeAllShow_NetworkNotice: boolean; // = true; 启用分类【全部】
    static typeAllName_NetworkNotice: string; // = "全部"; 分类【全部】的名称
    static typeAllCover_NetworkNotice: string; // = "asset/image/NetworkNotice/Box_3.png"; 分类【全部】的封面
    static isFadeIn_NetworkNotice1: boolean; // = true; 启用插件预设的淡入淡出动画
    static errorEvent_NetworkNotice: string; // = ""; 请求公告列表失败时触发事件
    static errorContentEvent_NetworkNotice: string; // = ""; 请求公告内容失败时触发事件
    static errorMessage_NetworkNotice: number; // = 0; 如果存在请求公告列表失败消息，绑定至
    static errorContentMessage_NetworkNotice: number; // = 0; 如果存在请求公告内容失败消息，绑定至
    static Ltrwp_GlobalBroadcastList: DataStructure_Ltrwp_BroadcastGroup[]; // = [];
    static Ltrwp_ScrollSpeed: number; // = 2; 广播滚动速度
    static Ltrwp_MessageIntervalMin: number; // = 50; 广播间隔-最小值(秒)
    static Ltrwp_MessageIntervalMax: number; // = 50; 广播间隔-最大值(秒)
    static Ltrwp_NoticeSound: string; // = ""; 广播音效
    static WfskpArrayListKey: number; // = 0; 显示数组面板键
    static WfskpArrayShowKey: number; // = 0; 显示数组详细键
    static missionAvailableIcon: string; // = ""; 任务插件 可接受任务 NPC头顶图标
    static missionCompletableIcon: string; // = ""; 任务插件 可交付任务 NPC头顶图标
    static missionInProgressIcon: string; // = ""; 任务插件 进行中任务 NPC头顶图标
}
class PlayerData {
    sceneObject: SceneObject;
    package: DataStructure_packageItem[]; // = [];
    gold: number; // = 0; 金币
    party: DataStructure_inPartyActor[]; // = [];
    aiMode: number; // = 1; 队员攻击模式
    aiVigilanceRange: number; // = 200; 警戒范围
    packageCapacity: number; // = 54; 背包容量
    ctrlActorIndex: number; // = 0; 当前控制的角色索引
    actorRecords: DataStructure_inPartyActor[]; // = [];
    持有日志: Module_日志[]; // = [];
    packageCapacityPage: number; // = 50; 背包每页容量
    achievementPoints: number; // = 0; 成就点数
    achievements: DataStructure_玩家成就[]; // = [];
    revealedAchievements: number[]; // = [];
    mission: DataStructure_mission[]; // = [];
    Lmkrt_TrackedMissions: number[]; // = [];
}